---
# file: deployment/playbooks/group_vars/all.yml
#
# Variables that are common for all deploys of this project
#
project_name: {{ project_name }}
python_version: 3.4
# pg_version: 9.4

users:
  - { name: 'vagrant', public_key: [] }
  - { name: 'devuser1', public_key: ['ssh-rsa longkeystring== devuser1@example.com'] }

{% verbatim %}
app_minions: "{{ groups['web'] | union(groups['worker']) }}"
{% endverbatim %}
ansible_sudo: true

db_host: localhost
